title: <p align="center"> Aakarsh Goel </p>
logo: /assets/img/logo.JPG

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  
  
  <br>   
  I'm working on Data Science, Software development 
  <br>
  </p>



theme: jekyll-theme-minimal
